# config.yml

# mdoel args
model_type:
  translate_from_pretrained
model:        
    pretrain_model_name_or_path: "facebook/mbart-large-50-many-to-many-mmt"
    device: cuda   

# trainning args
traininng:
  batch_size: 6               
  epochs: 1000          
  learning_rate: 0.00002   
  optimizer: AdamW              
  weight_decay: 0.1
  clip_max_norm: 0.5
  factor: 0.3
  patience: 15         
  device: cuda


dataset_type:
  translate
dataset:
  train_data_path: "data/train.jsonl"       
  test_data_path: "data/test.jsonl"       
  valid_data_path: "data/test.jsonl"       
  max_padding_length: 512


logging:
  log_interval: 100             
  save_dir: "./saved_model/translate_from_pretrained"   
